[theme]
primaryColor = "#2E236C"  # Medium slate blue (a bluish purple)
backgroundColor = "#FFFFFF"  # White
secondaryBackgroundColor = "#C8ACD6"  # Light cyan (a light bluish color)
textColor = "#17153B"  # Gray
font = "sans-serif" 

[server]
enableCORS = false
enableXsrfProtection = false
